### PR TITLE
Created database ER model

### LINKED ISSUE #3: Design database tables
Prepare ER diagram for database tables according to [this description](https://github.com/Dauren-Delmukhambetov/legendary-succotash/blob/master/docs/model.yaml)
You can add `md` file with diagram under `docs` folder in the project structure and send a PR

### PR DESCRIPTION
**Pull request by COCONUTmkII**
According to my personal experience and information on the internet, I decided to use ENUM as a data structure in the Roles table because with ENUM type I can use annotation Enumerated with an ENUM type in which I can change relation in my database, such as Integer or String value.

### CODE REVIEW

**Comment by Dauren-Delmukhambetov** [comment]
What is the relation between `User` and `UserRole`?
On which column they refer to each other?
If I ask you to count users number by roles (`admin: 10`, `user: 234`) how your SQL script would look like?

**Review by Dauren-Delmukhambetov — COMMENTED** [review]
Asked questions above

**Comment by Dauren-Delmukhambetov** [comment]
This PR related to task #3

**Comment by COCONUTmkII** [comment]
> What is the relation between `User` and `UserRole`?
> On which column they refer to each other?
> If I ask you to count users number by roles (`admin: 10`, `user: 234`) how your SQL script would look like?

1) Relationship between 'User' and 'UserRole' is One to One as we discussed it.
2) They will be referred to each other with a shared primary key. If you think thank this is a bad decision, I can make a "classical" relation with a foreign key :)
3) That's a good question! I think it might look like this if I will create a query with joins. Maybe there is a better solution, but I suggested this right now :)
`SELECT COUNT(u.id) AS user_count, r.role AS user_role FROM Users u INNER JOIN users_roles ur ON u.id = ur.id`

**Comment by Dauren-Delmukhambetov** [comment]
> > What is the relation between `User` and `UserRole`?
> > On which column they refer to each other?
> > If I ask you to count users number by roles (`admin: 10`, `user: 234`) how your SQL script would look like?
> 
> 1. Relationship between 'User' and 'UserRole' is One to One as we discussed it.
> 2. They will be referred to each other with a shared primary key. If you think thank this is a bad decision, I can make a "classical" relation with a foreign key :)
> 3. That's a good question! I think it might look like this if I will create a query with joins. Maybe there is a better solution, but I suggested this right now :)
>    `SELECT COUNT(u.id) AS user_count, r.role AS user_role FROM Users u INNER JOIN users_roles ur ON u.id = ur.id`

Thanks for your answers!
Regarding the shared primary key, I think it would be more beneficial for further extensibility to have PK for each table. I would opt for adding column `user_id` into the user roles table

**Review by Dauren-Delmukhambetov — COMMENTED** [review]
Are you sure about the naming of the primary key columns?
Usually, it refers to a simple `id` column, and using the `user_id` column in the `users` table can be confusing since it can be misinterpreted as a foreign key.
For example, having the `department_id` column in the `employee` table usually means that this column refers to `id` column in some `department` table

**Comment by COCONUTmkII** [comment]
> > > What is the relation between `User` and `UserRole`?
> > > On which column they refer to each other?
> > > If I ask you to count users number by roles (`admin: 10`, `user: 234`) how your SQL script would look like?
> > 
> > 
> > 
> > 1. Relationship between 'User' and 'UserRole' is One to One as we discussed it.
> > 2. They will be referred to each other with a shared primary key. If you think thank this is a bad decision, I can make a "classical" relation with a foreign key :)
> > 3. That's a good question! I think it might look like this if I will create a query with joins. Maybe there is a better solution, but I suggested this right now :)
> >    `SELECT COUNT(u.id) AS user_count, r.role AS user_role FROM Users u INNER JOIN users_roles ur ON u.id = ur.id`
> 
> Thanks for your answers!
> Regarding the shared primary key, I think it would be more beneficial for further extensibility to have PK for each table. I would opt for adding column `user_id` into the user roles table

Thank you for your remarks! I will create PK as you said. But are you sure, that I need to insert 'user_id ' in Roles table? Maybe it would be more appropriate to insert 'roles_id' in User table?

**Comment by COCONUTmkII** [comment]
> Are you sure about the naming of the primary key columns?
> Usually, it refers to a simple `id` column, and using the `user_id` column in the `users` table can be confusing since it can be misinterpreted as a foreign key.
> For example, having the `department_id` column in the `employee` table usually means that this column refers to `id` column in some `department` table

In my personal experience, I always named ID columns with the table name word. But I can change the names to the simple word "id". :)

**Comment by Dauren-Delmukhambetov** [comment]
> > > > What is the relation between `User` and `UserRole`?
> > > > On which column they refer to each other?
> > > > If I ask you to count users number by roles (`admin: 10`, `user: 234`) how your SQL script would look like?
> > > 
> > > 
> > > 
> > > 1. Relationship between 'User' and 'UserRole' is One to One as we discussed it.
> > > 2. They will be referred to each other with a shared primary key. If you think thank this is a bad decision, I can make a "classical" relation with a foreign key :)
> > > 3. That's a good question! I think it might look like this if I will create a query with joins. Maybe there is a better solution, but I suggested this right now :)
> > >    `SELECT COUNT(u.id) AS user_count, r.role AS user_role FROM Users u INNER JOIN users_roles ur ON u.id = ur.id`
> > 
> > 
> > Thanks for your answers!
> > Regarding the shared primary key, I think it would be more beneficial for further extensibility to have PK for each table. I would opt for adding column `user_id` into the user roles table
> 
> Thank you for your remarks! I will create PK as you said. But are you sure, that I need to insert 'user_id ' in Roles table? Maybe it would be more appropriate to insert 'roles_id' in User table?

Having `user_id` in `user_roles` table allow us to stay extensible. In case we need to introduce a user with multiple roles we will just change the relation between the two tables. Maybe I'm a bit over-engineering here, but nevertheless, I think it's a more common case to have users with multiple roles rather than only one

**Comment by Dauren-Delmukhambetov** [comment]
> > Are you sure about the naming of the primary key columns?
> > Usually, it refers to a simple `id` column, and using the `user_id` column in the `users` table can be confusing since it can be misinterpreted as a foreign key.
> > For example, having the `department_id` column in the `employee` table usually means that this column refers to `id` column in some `department` table
> 
> In my personal experience, I always named ID columns with the table name word. But I can change the names to the simple word "id". :)

Up to you

**Review by Dauren-Delmukhambetov — APPROVED** [review]
LGTM

**Pull request merged**
